name: readme-scribe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  readme-scribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - shell: cmd
        env:
          SUPER_SECRET: ${{ secrets.MARKSCRIBE_TOKEN }}
        run: |
          echo %SUPER_SECRET%

      - name: Generate README
        uses: muesli/readme-scribe@master
        env:
          # GITHUB_TOKEN: ${{ secrets.MARKSCRIBE_TOKEN }}
          GITHUB_TOKEN: ''
        with:
          template: 'README.gtpl'
          writeTo: 'README.md'

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MARKSCRIBE_TOKEN }}
        with:
          commit_message: 'readme-scribe: update README.md'